nama: CI

aktif: [dorong, alur kerja_pengiriman]

Pekerjaan:
  membangun:

    berjalan pada: windows-terbaru

    Langkah:
    - nama: Unduh
      jalankan: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - nama: Ekstrak
      jalankan: Perluas-Arsipkan ngrok.zip
    - nama: Otentikasi
      jalankan: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      lingkungan:
        NGROK_AUTH_TOKEN: ${{ rahasia.NGROK_AUTH_TOKEN }}
    - nama: Aktifkan TS
      jalankan: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-nama "fDenyTSConnections" -Nilai 0
    - jalankan: Enable-NetFirewallRule -DisplayGroup "Desktop Jarak Jauh"
    - jalankan: Set-ItemProperty -Jalur 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -nama "UserAuthentication" -Nilai 1
    - jalankan: Set-LocalUser -Nama "runneradmin" -Kata Sandi (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - nama: Buat Terowongan
      jalankan: .\ngrok\ngrok.exe tcp 3389
